### ISSUE TITLE
Translations links

### ISSUE THREAD

**Issue by habutre** [rogerdudler/git-guide#11]
Hey @rogerdudler could you consider put the label of links translation on each natural language instead of english. I think it's very nice, when a person looks to the guide his language is automacally understood

**Comment by rogerdudler** [comment]
I agree. I thought about this yesterday. Can you help with your translation?

**Comment by habutre** [comment]
Of course Roger!
leave this work with me

On 1/13/12, Roger Dudler
reply@reply.github.com
wrote:

> I agree. I thought about this yesterday. Can you help with your translation?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rogerdudler/git-guide/issues/11#issuecomment-3480497

## 

_Rogério Ramos da Silva_
msn: habutre@hotmail.com
skype: habutre
email alternativo: ramos_roger@ig.com.br

OBS: Qualquer anomalia, irregularidade ou desfiguração de documento anexo,
pode dar-se devido a alguma incompatibilidade da suite open source
OpenOffice utilizada como alternativa à suite office da Microsoft®

"_Fé inabalável é somente
aquela que pode encarar a
razão face-a-face em qualquer
época da Humanidade_".

P Antes de imprimir pense em seu compromisso com o Meio Ambiente
