### ISSUE TITLE
git add -A vs git add .

### ISSUE THREAD

**Issue by robophil** [rogerdudler/git-guide#129]
Which is better to use ?

**Comment by wuilmerbolivar** [comment]
git add -i ?¿Ventajas - Desventajas de estos metodos?

**Comment by robophil** [comment]
I don't speak spanish.. git add -i, what does that do?

**Comment by samrm111** [comment]
`git add .` will add any files that are new or modified to the staged changes. `git add -A` does the same thing but it will also stage removed files.

**Comment by robophil** [comment]
ok, Thanks

**Comment by khitermedachraf** [comment]
so (git add *) does not exist
(git add .) =(git add -A) it means : stage all ( new , modified , deleted ) files
