### ISSUE TITLE
This page is using a font that not support Vietnamese

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [rogerdudler/git-guide#162]
![image](https://user-images.githubusercontent.com/16047808/45203575-cdb05200-b2a6-11e8-9840-df4d2737cdb7.png)

**Comment by msscsh** [comment]
@Meigyoku-Thmn this was solved? Can you close this issue?

**Comment by Meigyoku-Thmn** [comment]
> @Meigyoku-Thmn this was solved? Can you close this issue?

Yeah, it works now. (Wow, 6 years ago)

**Comment by msscsh** [comment]
It was fixed a while ago, the issue remained open. Could you close it?
